### PR TITLE
[16.0] [MIG] hr_leave_custom_hour_interval: Migration to 16.0

### PR DESCRIPTION
**Pull request by luisDIXMIT**
Standard migration

- Added CONFIGURE.rst readme file and modified USAGE.rst
- Added unit test

@etobella

### CODE REVIEW

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Review by janikvonrotz — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please rebase to check the CI error.

**Comment by luisDIXMIT** [comment]
@pedrobaeza fixed!!

**Pull request merged**
