### PR TITLE
[16.0][MIG] hr_holidays_summary_email

### PR DESCRIPTION
**Pull request by JasminSForgeFlow**
Standard Migration

@ForgeFlow

Depends on:

- https://github.com/OCA/hr-holidays/pull/120

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
It depends on https://github.com/OCA/hr-holidays/pull/120.

Also, please fix PR title to 16.0.

**Comment by JasminSForgeFlow** [comment]
> It depends on #120.
> 
> Also, please fix PR title to 16.0.

Done 👍

**Review by JordiBForgeFlow — APPROVED** [review]
We have now used in production for quite a long time

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza can you merge this PR?

**Review by pedrobaeza — APPROVED** [review]
/ocabot migration hr_holidays_summary_email
/ocabot merge nobump

**Pull request merged**
