### PR TITLE
[14.0][MIG] hr_holidays_settings

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Standard migration

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by OsoTranquilo — APPROVED** [review]

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Did anyone cancelled the merge? I think it's ready to merge.

**Comment by JordiMForgeFlow** [comment]
Hi @nimarosa 

I think it simply failed, maybe we could retry :)

**Comment by gjotten** [comment]
@JordiMForgeFlow @nimarosa @MiquelRForgeFlow the module migrated here exists in OCA/hr repository already: https://github.com/OCA/hr/pull/1111

Leading to build failing on one of our crontabbed instances; git aggregate gives us:

```
AddonsConfigError: Addon hr_holidays_settings defined in several repos {'OCA/hr-holidays', 'OCA/hr'}
Traceback (most recent call last):
  File "/home/ubuntu/odoo/common/entrypoint", line 39, in <module>
    subprocess.check_call(command)
  File "/home/ubuntu/odoo/.pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/ubuntu/odoo/common/entrypoint.d/40-addons-link' returned non-zero exit status 1.
```

I don't believe we want this?

**Pull request merged**
