### PR TITLE
[13.0][MIG] hr_holidays_leave_auto_approve

### PR DESCRIPTION
**Pull request by astirpe**
Includes https://github.com/OCA/hr/pull/778

Supersedes https://github.com/OCA/hr/pull/704

Replaces https://github.com/OCA/hr-holidays/pull/3

### CODE REVIEW

**Review by emagdalenaC2i — APPROVED** [review]
LGTM

**Comment by emagdalenaC2i** [comment]
@espo-tony @nikul-serpentcs @tafaRU @CasVissers-360ERP @Saran440 and @MiquelRForgeFlow Please, could you review this PR?

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM but the "pre-commit" commit could be named better

**Review by CasVissers-360ERP — APPROVED** [review]

**Review by Saran440 — COMMENTED** [review]
/ocabot merge nobump

**Comment by emagdalenaC2i** [comment]
@Saran440 seems you can't merge this PR.
Please @OCA/community-maintainers , could someone check and merge this PR?

**Review by Saran440 — APPROVED** [review]

**Pull request merged**
