### PR TITLE
[15.0][ADD] hr_holidays_public_overtime

### PR DESCRIPTION
**Pull request by hbrunn**
This module adds support for public holidays in Odoo's overtime calculation.

Without this, public holidays are treated as normal work days from the PoV of overtime calculation.

### CODE REVIEW

**Review by HekkiMelody — APPROVED** [review]
Code review, LGTM

**Review by albig — APPROVED** [review]

**Comment by tv-openbig** [comment]
@hbrunn I can confirm it works. I have tested this in context of the following Pull request: https://github.com/OCA/hr-attendance/pull/140

**Pull request merged**
