### PR TITLE
[ADD][16.0] New module hr_leave_type_code

### PR DESCRIPTION
**Pull request by HekkiMelody**
Small module adding a `code` field to `hr_leave_type`

### CODE REVIEW

**Comment by nimarosa** [comment]
@aleuffre please rebase the PR to the base branch.

**Comment by HekkiMelody** [comment]
> @aleuffre please rebase the PR to the base branch.

Done! Thank you for your interest in my PR!

Do you know how I can give maintainers push rights on my branches? This has been a recurring problem in multiple PRs...

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
