### PR TITLE
[MIG][14.0] hr_holidays_leave_repeated

### PR DESCRIPTION
**Pull request by remi-filament**

### CODE REVIEW

**Review by JulianaPoudou — APPROVED** [review]

**Review by njeudy — APPROVED** [review]
Ok for me "rapid code review" and test on local database. +1

**Review by kluna1998 — APPROVED** [review]

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Code review look good. Checks okay. 

Merging. 

/ocabot merge nobump

**Pull request merged**
