### PR TITLE
[16.0][FIX] hr_holidays_public: fixed action_validate() override

### PR DESCRIPTION
**Pull request by dalonsod**
Forward-port of #114

### CODE REVIEW

**Comment by dalonsod** [comment]
Tests fail due to `hr_holidays_leave_auto_approve` addon.

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you check CI?

**Comment by dalonsod** [comment]
Done!

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
