### PR TITLE
[13.0][ADD] hr_holidays_summary_email

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Module to send a daily or weekly email to employees with a summary of the leaves of the employees in the same company.

- [x] Add tests
- [x] Display information on the hours for hourly tracked leaves

### CODE REVIEW

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM 👍🏽

**Review by MateuGForgeFlow — APPROVED** [review]

**Review by JuanyDForgeflow — APPROVED** [review]
LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by JoanSForgeFlow — APPROVED** [review]
Great idea @JordiMForgeFlow!

**Pull request closed without merging**
