### PR TITLE
[17.0][MIG] hr_holidays_natural_period: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**

### CODE REVIEW

**Comment by carlos-lopez-tecnativa** [comment]
@peluko00 please check the CI. The tests are failing.

When I create a new leave, I get an error.
image


@Tecnativa TT50070

**Comment by peluko00** [comment]
> @peluko00 please check the CI. The tests are failing.
> 
> When I create a new leave, I get an error. image
> 
> @Tecnativa TT50070

I know but in my dev environment the test aren't failing and the module works good

**Review by carlos-lopez-tecnativa — CHANGES_REQUESTED** [review]
@peluko00 the computation seems incorrect from my perspective. Please compare version 16 with version 17.

V16
image

V17
image

If an employee works from Monday to Friday, it counts as 7 days according to the employee calendar. However, this module should not consider the employee calendar. Therefore, from the 1st to the 10th should be counted as 10 natural days.

**Comment by peluko00** [comment]
> @peluko00 the computation seems incorrect from my perspective. Please compare version 16 with version 17.
> 
> V16 image
> 
> V17 image
> 
> If an employee works from Monday to Friday, it counts as 7 days according to the employee calendar. However, this module should not consider the employee calendar. Therefore, from the 1st to the 10th should be counted as 10 natural days.

I fix that problem but the tests are failing but no in dev environment

**Comment by carlos-lopez-tecnativa** [comment]
> 
> I fix that problem but the tests are failing but no in dev environment

@peluko00 I ran the tests on my local machine and encountered the same error. Could you please share how you're running the tests since they seem to be working for you?
image

**Comment by peluko00** [comment]
> > I fix that problem but the tests are failing but no in dev environment
> 
> @peluko00 I ran the tests on my local machine and encountered the same error. Could you please share how you're running the tests since they seem to be working for you? image

I ran the tests in my local machine with the normal command for executing tests and only installing hr_holidays_natural_period without installing any more modules.

image

**Comment by pedrobaeza** [comment]
@peluko00 there should be something incorrect in your way to run tests, as the log is not correct:

- Starting with, there's only 2 tests, while your log talks about 4 tests.
- There's no trace in the log about the execution of the test `odoo.addons.hr_holidays_natural_period.tests.test_hr_leave`, while it should be.

Maybe you have some touched Odoo version for running the tests or you are not executing the proper command? If you are putting test tags, make sure you put the correct ones.

**Comment by peluko00** [comment]
> @peluko00 there should be something incorrect in your way to run tests, as the log is not correct:
> 
> * Starting with, there's only 2 tests, while your log talks about 4 tests.
> * There's no trace in the log about the execution of the test `odoo.addons.hr_holidays_natural_period.tests.test_hr_leave`, while it should be.
> 
> Maybe you have some touched Odoo version for running the tests or you are not executing the proper command? If you are putting test tags, make sure you put the correct ones.

The 4 tests only i see in both images is at the final.
I send another picture with the complete log and i execute the tests with the normal command acording to documentation.

image

**Comment by pedrobaeza** [comment]
But are you testing it on installation? Anyway, there's a problem, as stated in this CI or local testing on my colleague, so this migration is not correct while the problem is not fixed. And the test failure highlights that the module may not be working.

**Comment by peluko00** [comment]
> But are you testing it on installation? Anyway, there's a problem, as stated in this CI or local testing on my colleague, so this migration is not correct while the problem is not fixed. And the test failure highlights that the module may not be working.

I follow the next steps:

- Create demo database
- Install the module
- Run the tests

All tests are running but i don't know why don't throws an error.

**Comment by pedrobaeza** [comment]
You have to run tests at the same time of the installation: `odoo -i hr_holidays_natural_period --test-enable --test-tags=hr_holidays_natural_period --workers=0 --stop-after-init`.

**Comment by carlos-lopez-tecnativa** [comment]
Hi, @peluko00, have you reviewed the error in the test? Can I help you with anything?

**Comment by peluko00** [comment]
> Hi, @peluko00, have you reviewed the error in the test? Can I help you with anything?

Yes, i review but  i can't find the error

**Review by victoralmau — CHANGES_REQUESTED** [review]
I tried in runboat and it doesn't work (that's why the tests fail too)

ejemplo

The days that should be displayed are 31

**Comment by carlos-lopez-tecnativa** [comment]
Superseded by https://github.com/OCA/hr-holidays/pull/141

**Pull request closed without merging**
