### PR TITLE
[14.0][ADD] hr_holidays_summary_email

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
adding it to V14 instead of V13 (#74)

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by JoanSForgeFlow — APPROVED** [review]

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Review by GuillemCForgeFlow — APPROVED** [review]
LGTM! 👍🏽

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by JordiMForgeFlow** [comment]
Hi @pedrobaeza 

We have been using this module for some weeks now, could you review and merge if possible? :)

**Comment by pedrobaeza** [comment]
Merging based on existing reviews:

/ocabot merge nobump

**Pull request merged**
