### PR TITLE
[13.0][IMP] hr_holidays_credit: add unit in form selection widget & plurals management

### PR DESCRIPTION
**Pull request by maisim**
port from 12.0

https://github.com/OCA/hr/pull/1356

### CODE REVIEW

**Comment by maisim** [comment]
Hi @alexey-pelykh !

I ported the module by hand because the repo change is not managed by oca-port.

Hi tested functionalities from the runboat build, all seems ok.

I don't know why the test fail on __init__.py has it is not modified in the PR

Can you have a look ? Thanks a lot !

**Comment by alexey-pelykh** [comment]
@maisim please don't forget to do the `pre-commit run -a` :) other than that looks good

**Review by alexey-pelykh — APPROVED** [review]
LGTM

**Comment by maisim** [comment]
> 
> I ported the module by hand because the repo change is not managed by oca-por

I discover that oca-port is now able to manage the port even it the repo ha changed \o/

https://github.com/OCA/oca-port#using

**Pull request merged**
