### PR TITLE
[15.0][IMP] hr_holidays_public: include public holidays in employee's _get_unusual_days

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
This is useful in the time off overview calendar, from:
image

to:
image

cc @forgeflow

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
code review 👍🏼

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Not sure unusual days is for that. cc @victoralmau

**Review by victoralmau — CHANGES_REQUESTED** [review]
I do not agree with this change. Although the `_get_unusual_days()` https://github.com/odoo/odoo/blob/3a28e5b0adbb36bdb1155a6854cdfbe4e7f9b187/addons/hr/models/hr_employee.py#L442 method perhaps does not clarify much, it is important to explain what is currently happening in the dashboard with the different options:
- Unusual days based on the employee's work schedule: they are shown in gray color.
ejemplo
- Time Off days: The overlay event is shown on the days that correspond.
ejemplo-ausencia
- Public holidays: The same event is shown as for time off days.

**IMO** I think it is clear that public holidays should be treated as holidays and not as non-working days.

**Comment by victoralmau** [comment]
Extra comment: If we access from the “Time off”
 smart-button of an employee to the dashboard, the public holidays are shown in gray color.
ejemplo

**Comment by AaronHForgeFlow** [comment]
> IMO I think it is clear that public holidays should be treated as holidays and not as non-working days.

Ok, my use case is that all public holidays are non-working days across the company, and in that case it made sense to show it as non working day for all,  but I understand that is not the most "generic" case.  I am closing this then and move the feature to another place. Thank you for the review.

**Comment by victoralmau** [comment]
Sorry, I didn't agree with adding this as a general thing, maybe being something per company (disabled by default) with `res.config.settings` could be a good contribution. what do you all think?

**Comment by pedrobaeza** [comment]
Even at company level, public holidays may vary depending on the employee locations, so I don't think this should be added this way, even with a configuration switch.

**Pull request closed without merging**
