### PR TITLE
[16.0] [MIG] hr_holidays_auto_extend: Migration to 16.0

### PR DESCRIPTION
**Pull request by luisDIXMIT**
Standard migration.
Extended test coverage.

@etobella

### CODE REVIEW

**Review by gbrito — APPROVED** [review]

**Review by etobella — APPROVED** [review]
/ocabot merge nobump

**Comment by etobella** [comment]
@luisDIXMIT can you rebase and then we can check it?

**Comment by luisDIXMIT** [comment]
@etobella comments attended

**Pull request merged**
