### PR TITLE
[17.0][FIX] hr_holidays_public: fixed action_validate() override

### PR DESCRIPTION
**Pull request by dalonsod**
Forward-port of #115

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Was this already fixed?

**Comment by dalonsod** [comment]
Tested in 17.0 runboat without this fix the bug case (trying to validate leaves that belong to more than one employee):

imagen

still fires an error:

imagen

Then, the fix seems to be required.

**Comment by dalonsod** [comment]
Anyway I'll take a look at existing merge conflicts ASAP and update this PR

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Comment by pedrobaeza** [comment]
Can you check CI?

**Comment by dalonsod** [comment]
Checked, and I don't know how to fix it. It fails when `hr_holidays` addon is trying to notify leave approval in a way I don't understand which modification in current code could lead to this error.

@dariodelzozzo could you help us?

**Comment by xaviedoanhduy** [comment]
Hello @dalonsod, this issue has been fixed already in [this commit](https://github.com/OCA/hr-holidays/commit/5770e4bc7326cd8431092ac6e2dad9ddcef6d5fa), So can you need to rebase this PR for tests to be green?

**Comment by pedrobaeza** [comment]
The rebase is done by the bot, so trying again

/ocabot merge patch

**Pull request merged**
