### PR TITLE
[15.0][FIX] hr_holidays_public: Run tests with user timezone.

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please don't mix in the same commit the copier update with the other fix.

**Comment by pedrobaeza** [comment]
Please rebase and remove the pre-commit stuff

**Comment by sergio-teruel** [comment]
@pedrobaeza Ready!!

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking to solve the CI:

/ocabot merge patch

**Pull request merged**
