### PR TITLE
[14.0][FIX] hr_holidays_summary_email: allow users to self edit setting

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**

### CODE REVIEW

**Review by JoanSForgeFlow — APPROVED** [review]
LGTM!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza Can you merge this one, please?

**Comment by JordiBForgeFlow** [comment]
@JordiMForgeFlow can you forward port to the pr in 15

**Comment by JordiMForgeFlow** [comment]
@JordiBForgeFlow I already included it in the migration PR: https://github.com/OCA/hr-holidays/pull/108

**Comment by JordiBForgeFlow** [comment]
Thanks!

**Pull request merged**
