### PR TITLE
[15.0][MIG] hr_holidays_natural_period: Migration to 15.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 15.0

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT40362

### CODE REVIEW

**Review by nimarosa — APPROVED** [review]
Please check pre-commit

**Review by pedrobaeza — APPROVED** [review]
Tested on runboat.

What about adding a demo type for being faster on reviews?

**Comment by victoralmau** [comment]
> Tested on runboat.
> 
> What about adding a demo type for being faster on reviews?

Ok, demo data added.

**Comment by nimarosa** [comment]
Also done functional test. 
Everything green and demo data on. Think we can merge now. 

/ocabot merge nobump

**Pull request merged**
