### PR TITLE
[13.0][FIX] hr_holidays_natural_period: Prevent error in form leave when employee is not set yet.

### PR DESCRIPTION
**Pull request by victoralmau**
Prevent error in form leave when employee is not set yet.

Please @pedrobaeza and @Yajo can you review it?

@Tecnativa TT29243

### CODE REVIEW

**Comment by victoralmau** [comment]
Ping @joao-p-marques

**Review by yajo — APPROVED** [review]
Code looks OK, although there are no STR and I don't know what/if it fixes.

**Comment by pedrobaeza** [comment]
Well, the minimal STR are `Prevent error in form leave when employee is not set yet.`

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@victoralmau next time, you can put the steps to the reproduce in a less summarized mode, being complete steps:

/ocabot merge patch

**Pull request merged**
